name: windows-x86-debug

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'

# https://github.com/GuillaumeFalourd/setup-windows10-sdk-action/issues/3

jobs:
  build-windows-x86-debug:
    runs-on: windows-latest
    steps:
      - name: Setup Windows 10 SDK version 10.0.20348.0
        uses: GuillaumeFalourd/setup-windows10-sdk-action@dev
        with:
          sdk-version: 20348
      - name: Checkout sources
        run: |
          git clone https://github.com/google/angle .
      - name: Fetch depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - name: Build
        shell: cmd
        run: |
          set PATH=%cd%\depot_tools;%PATH%
          set DEPOT_TOOLS_WIN_TOOLCHAIN=0
          set vs2019_install=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
          set WINDOWSSDKDIR=C:\Program Files (x86)\Windows Kits\10
          cmd /c gclient
          cmd /c python scripts/bootstrap.py
          cmd /c gclient sync
          cmd /c gn gen out/Debug --args="is_debug=true target_cpu=\"x86\" angle_build_all=false"
          cmd /c autoninja -C out/Debug
      - name: Pack
        shell: bash
        run: |
          mkdir angle-windows-x86
          mkdir angle-windows-x86/dist
          rm -rf out/Debug/cdb
          rm -rf out/Debug/gen
          rm -rf out/Debug/obj
          rm -rf out/Debug/args.gn
          rm -rf out/Debug/build.ninja
          rm -rf out/Debug/build.ninja.d
          rm -rf out/Debug/toolchain.ninja
          rm -rf out/Debug/environment.*
          mv -f out/Debug/* angle-windows-x86/dist/
          cp -rf include angle-windows-x86/
          find angle-windows-x86 -name ".clang-format" -delete
          find angle-windows-x86 -name "*.md" -delete
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: angle-windows-x86
          path: angle-windows-x86
